   //宠物搜索
   var gougou=[{
            name:'体型',
            type:'base',
            list:[
            {
                name:'小型',
                id:'31'                
            },{
                name:'中型',
                id:'32'                
            },{
                name:'大型',
                id:'33'                
            }]
        },{
            name:'毛长',
            type:'base',
            list:[{
                name:'无毛',
                id:'34'
            },{
                name:'短毛',
                id:'35'
            },{
                name:'长毛',
                id:'36'
            }]
        },{
            name:'毛色',
            type:'base',
            list:[{
                name:'白色',
                id:'37'
            },{
                name:'黑色',
                id:'38'
            },{
                name:'灰色',
                id:'89'
            },{
                name:'黄色',
                id:'39'
            },{
                name:'褐色',
                id:'40'
            },{
                name:'红棕色',
                id:'43'
            },{
                name:'咖啡色',
                id:'44'
            },{
                name:'陨石色',
                id:'45'
            },{
                name:'貂色',
                id:'46'
            },{
                name:'其他颜色',
                id:'47'
            }]
        },{
            name:'功能',
            type:'base',
            list:[{
                name:'伴侣犬',
                id:'48'
            },{
                name:'牧羊犬',
                id:'49'
            },{
                name:'梗类犬',
                id:'50'
            },{
                name:'守卫犬',
                id:'51'
            },{
                name:'枪猎犬',
                id:'52'
            },{
                name:'看家犬',
                id:'53'
            },{
                name:'雪橇犬',
                id:'54'
            },{
                name:'玩赏犬',
                id:'55'
            },{
                name:'搜救犬',
                id:'56'
            },{
                name:'导盲犬',
                id:'57'
            },{
                name:'其他',
                id:'58'
            }]
        },{
            name:'特点',
            type:'detail',
            list:[{
                name:'不爱叫',
                id:'4'
            },{
                name:'无体味',
                id:'8'
            },{
                name:'少掉毛',
                id:'6'
            },{
                name:'少口水',
                id:'27'
            },{
                name:'易训练',
                id:'26'
            },{
                name:'粘人',
                id:'18'
            },{
                name:'耐寒',
                id:'20'
            },{
                name:'耐热',
                id:'22'
            },{
                name:'爱护家',
                id:'16'
            }]
        },{
            name:'友善程度',
            type:'detail',
            list:[{
                name:'一般',
                id:'2'
            },{
                name:'非常',
                id:'3'
            },{
                name:'脾气暴躁',
                id:'1'
            }]
        },{
            name:'饲养难度',
            type:'detail',
            list:[{
                name:'容易',
                id:'14'
            },{
                name:'一般',
                id:'13'
            },{
                name:'难',
                id:'12'
            }]
        },{
            name:'额外需求',
            type:'detail',
            list:[{
                name:'需造型',
                id:'11'
            },{
                name:'需陪伴',
                id:'30'
            },{
                name:'需运动',
                id:'24'
            }]
        }];
    var maomao=[{
        name:'体型',
        type:'base',
        list:[{
            name:'小型',
            id:'31'
        },{
            name:'中型',
            id:'32'
        },{
            name:'大型',
            id:'33'
        }]
    },{
        name:'毛长',
        type:'base',
        list:[{
            name:'无毛',
            id:'34'
        },{
            name:'短毛',
            id:'35'
        },{
            name:'长毛',
            id:'36'
        }]
    },{
        name:'毛色',
        type:'base',
        list:[{
            name:'白色',
            id:'37'
        },{
            name:'黑色',
            id:'38'
        },{
            name:'蓝色',
            id:'60'
        },{
            name:'黄色',
            id:'39'
        },{
            name:'褐色',
            id:'40'
        },{
            name:'重点色',
            id:'61'
        },{
            name:'渐层色',
            id:'62'
        },{
            name:'虎斑',
            id:'63'
        },{
            name:'其他颜色',
            id:'47'
        }]
    },{
        name:'特点',
        type:'detail',
        list:[{
            name:'不爱叫',
            id:'4'
        },{
            name:'无体味',
            id:'8'
        },{
            name:'少掉毛',
            id:'6'
        },{
            name:'少口水',
            id:'27'
        },{
            name:'易训练',
            id:'26'
        },{
            name:'粘人',
            id:'18'
        },{
            name:'耐寒',
            id:'20'
        },{
            name:'耐热',
            id:'22'
        },{
            name:'爱护家',
            id:'16'
        }]
    },{
        name:'友善程度',
        type:'detail',
        list:[{
            name:'一般友善',
            id:'2'
        },{
            name:'非常友善',
            id:'3'
        },{
            name:'脾气暴躁',
            id:'1'
        }]
    },{
        name:'饲养难度',
        type:'detail',
        list:[{
            name:'容易',
            id:'14'
        },{
            name:'一般',
            id:'13'
        },{
            name:'难',
            id:'12'
        }]
    },{
        name:'额外需求',
        type:'detail',
        list:[{
            name:'需造型',
            id:'11'
        },{
            name:'需陪伴',
            id:'30'
        },{
            name:'需运动',
            id:'24'
        }]
    }];
    var tuzi=[{
        name:'体型',
        type:'base',
        list:[{
            name:'小型',
            id:'31'
        },{
            name:'中型',
            id:'32'
        },{
            name:'大型',
            id:'33'
        }/*,{
            name:'巨型',
            id:'85'
        }*/]
    },{
        name:'毛长',
        type:'base',
        list:[{
            name:'短毛',
            id:'35'
        },{
            name:'长毛',
            id:'36'
        }]
    },{
        name:'毛色',
        type:'base',
        list:[{
            name:'白色',
            id:'37'
        },{
            name:'黑色',
            id:'38'
        },{
            name:'灰色',
            id:'89'
        },{
            name:'棕色',
            id:'85'
        },{
            name:'黄色',
            id:'39'
        },{
            name:'其他颜色',
            id:'47'
        }]
    },{
        name:'外貌特征',
        type:'base',
        list:[{
            name:'垂耳',
            id:'65'
        },{
            name:'立耳',
            id:'66'
        }]
    },{
        name:'饲养难度',
        type:'detail',
        list:[{
            name:'容易',
            id:'14'
        },{
            name:'一般',
            id:'13'
        },{
            name:'难',
            id:'12'
        }]
    }];
var shulei=[{
        name:'体型',
        type:'base',
        list:[{
            name:'小型',
            id:'31'
        },{
            name:'中型',
            id:'32'
        },{
            name:'大型',
            id:'33'
        }]
    },{
        name:'毛色',
        type:'base',
        list:[{
            name:'白色',
            id:'37'
        },{
            name:'灰色',
            id:'89'
        },{
            name:'黑色',
            id:'38'
        },{
            name:'黄色',
            id:'39'
        },{
            name:'其他颜色',
            id:'47'
        }]
    },{
        name:'特点',
        type:'base',
        list:[{
            name:'娇小可爱',
            id:'67'
        },{
            name:'憨厚',
            id:'68'
        },{
            name:'活泼好动',
            id:'69'
        }]
    },{
        name:'种类',
        type:'base',
        list:[{
            name:'仓鼠',
            id:'70'
        },{
            name:'豚鼠',
            id:'71'
        },{
            name:'花栗鼠',
            id:'72'
        },{
            name:'松鼠',
            id:'73'
        },{
            name:'龙猫',
            id:'101'
        },{
            name:'其他',
            id:'58'
        }]
    },{
        name:'友善程度',
        type:'detail',
        list:[{
            name:'一般友善',
            id:'2'
        },{
            name:'非常友善',
            id:'3'
        },{
            name:'脾气暴躁',
            id:'1'
        }]
    }];
    var chongwuniao=[{
        name:'体型',
        type:'base',
        list:[{
                name:'小型',
                id:'31'                
            },{
                name:'中型',
                id:'32'                
            },{
                name:'大型',
                id:'33'                
            }]
    },{
        name:'毛色',
        type:'base',
        list:[{
            name:'白色',
            id:'37'
        },{
            name:'黑色',
            id:'38'
        },{
            name:'黄色',
            id:'39'
        },{
            name:'绿色',
            id:'41'
        },{
            name:'红色',
            id:'82'
        },{
            name:'灰色',
            id:'89'
        },{
            name:'蓝色',
            id:'60'
        },{
            name:'其他颜色',
            id:'47'
        }]
    },{
        name:'特点',
        type:'base',
        list:[{
            name:'叫声悦耳',
            id:"74"
        },{
            name:'颜色丰富',
            id:'75'
        },{
            name:'会说话',
            id:'76'
        }]
    },{
        name:'种类',
        type:'base',
        list:[{
            name:'雀类',
            id:'77'
        },{
            name:'鸽类',
            id:'78'
        },{
            name:'鹦鹉类',
            id:"79"
        }]
    },{
        name:'品种类型',
        type:'base',
        list:[{
            name:'常见品种',
            id:'80'
        },{
            name:'稀有品种',
            id:'81'
        }]
    }];
   var chongwugui=[{
    name:'生活环境',
    type:'base',
    list:[{
        name:'陆地',
        id:'90'
    },{
        name:'水生',
        id:'91'
    },{
        name:'两栖',
        id:'92'
    }]
   },{
    name:'品种类型',
    type:'base',
    list:[{
        name:'常见品种',
        id:'80'
    },{
        name:'稀有品种',
        id:'81'
    }]
   },{
    name:'饲养难度',
    type:'detail',
    list:[{
        name:'容易',
        id:'14'
    },{
        name:'一般',
        id:'13'
    },{
        name:'难',
        id:'12'
    }]
   },{
    name:'友善程度',
    type:'detail',
    list:[{
        name:'一般友善',
        id:'2'
    },{
        name:'非常友善',
        id:'3'
    },{
        name:'脾气暴躁',
        id:'1'
    }]
   }];
   var chongwuyu=[{
    name:'颜色',
    type:'base',
    list:[{
        name:'红色',
        id:'82'
    },{
        name:'金色',
        id:'83'
    },{
        name:'银色',
        id:'84'
    },{
        name:'斑纹',
        id:'93'
    },{
        name:'黑色',
        id:'38'
    },{
        name:'橙色',
        id:'93'
    },{
        name:'其他颜色',
        id:'93'
    }]
   },{
    name:'尾巴形状',
    type:'base',
    list:[{
        name:'梳型',
        id:'94'
    },{
        name:'扇形',
        id:'95'
    },{
        name:'蝶尾',
        id:'96'
    },{
        name:'燕尾',
        id:'97'
    },{
        name:'凤尾',
        id:'100'
    },{
        name:'其他',
        id:'97'
    }]
   },{
    name:'品种类型',
    type:'base',
    list:[{
        name:'常见品种',
        id:"80"
    },{
        name:'稀有品种',
        id:'81'
    }]
   },{
    name:'生活环境',
    type:'base',
    list:[{
        name:'淡水',
        id:'98'
    },{
        name:'海水',
        id:'99'
    }]
   },{
    name:'饲养难度',
    type:'detail',
    list:[{
        name:'容易',
        id:'14'
    },{
        name:'一般',
        id:'13'
    },{
        name:'难',
        id:'12'
    }]
   }];
   var qita=[{
    name:'种类',
    type:'base',
    list:[{
        name:'鼬科动物',
        id:'102'
    },{
        name:'蜥蜴',
        id:'104'
    },{
        name:'刺猬',
        id:'105'
    },{
        name:'蜗牛',
        id:'106'
    },{
        name:'蜘蛛',
        id:'107'
    },{
        name:'蛇',
        id:'108'
    },{
        name:'其他',
        id:'109'
    }]
   }];
   var typeMap={
    1:'gougou',
    2:'maomao',
    3:'tuzi',
    4:'shulei',
    5:'qita',
    6:'chongwuniao',
    7:'chongwugui',
    8:'chongwuyu'
   }
   var petType=typeMap[petRaceId];
   var filterMap={
        gougou:gougou,
        maomao:maomao,
        tuzi:tuzi,
        shulei:shulei,
        chongwuniao:chongwuniao,
        chongwugui:chongwugui,
        chongwuyu:chongwuyu,
        qita:qita
   }
   var filterTpl='<&$(data).each(function(i,el){&><li><span class="subfilter-t"><&=el.name&>:</span>'+
                 '<div class="subfilter-itms" data-type="<&=el.type&>"><span class="itm active" data-itm="0">不限</span>'+
                 '<&$(el.list).each(function(j,itm){&>'+
                 '<span class="itm"  data-itm="<&=itm.id&>"><&=itm.name&></span><&});&>'+
                 '</div></li><&});&>';
   var baseInfo = [];
   var detailInfo = [];
   var keyword = '';
   var curr=pageNum;
   var $filterMenu=$('.s-filter-menu>a');
   var clickStatUrl='/api/incrPetClickNum.do'
   var filter={
        data:filterMap[petType]
   }
   pet.banpage=8;
   $('.pet-s-form').append('<a class="s-btn j-searchBtn" href="javascript:void(0)"></a>')
   $filterMenu.removeClass('current');
   $('.s-filter-menu>a[data-key="'+petRaceId+'"]').addClass('current');
   $('.pet-s-subfilter').html(D.utils.render(filterTpl,filter));
   $('body').on('click', '.j-link',function(event) {
       var key=$(this).data('id');
       $.get(clickStatUrl+'?petBreedId='+key, function(data) {
           /*optional stuff to do after success */
       });
   });
   $('.j-searchBtn').on('click',function(event) {
       event.preventDefault();
      goSearch();
   });
   $('.subfilter-itms .itm').on('click', function(event) {
       event.preventDefault();
       /* Act on the event */
       if ($(this).hasClass('active')) {
           return false;
       }
       $(this).addClass('active').siblings('.itm').removeClass('active');
       baseInfo = [];
       detailInfo = [];
       $('.subfilter-itms').each(function(index, el) {
           var activeItm = $(this).find('.itm.active');
           var itmId=activeItm.data('itm');
           if ($(this).data('type') === 'base'&&itmId!='0') {
               baseInfo.push(itmId);
           } if ($(this).data('type') === 'detail'&&itmId!='0') {
               detailInfo.push(itmId);
           }
       });
       curr=1;
       goSearch();
   });
   $('.j-sInput').keyup(function(event) {
       /* Act on the event */
       switch(event.keyCode) {
            case 13:
                goSearch();
            default:
                break;
        }
   }).val('');
   var search = function(pageNum, cb) {
        var sNoTpl='<div class="s-rs-none">\
                                    <h3>抱歉，没有找到符合条件的相关宠物</h3>\
                                    <p>建议您 ：</p>\
                                    <p>1、减少筛选条件可获得更多搜索结果；</p>\
                                    <p>2、检查是否输入错别字；</p>\
                                    <p>3、到“<a href="/pet">宠物大全</a>”再看看。</p>\
                                </div>';
        var sTpl = '<ul class="s-rs-ul"><&$(list).each(function(index,itm){var baseInfo=itm.baseInfo;&><li><a target="_blank" href="/pet/breed-<&=itm.petBreedId&>.html" data-id="<&=itm.petBreedId&>" class="j-link"><img class="pic" src="<&=itm.icon&>_s200" alt="<&=itm.name&>"></a>' +
           '<div class="info">' +
           '<div class="info-price">' +
           '<p class="t">参考价格</p><p class="num"><&=itm.price&></p></div>' +
           '<p class="info-t"><a target="_blank" href="/pet/breed-<&=itm.petBreedId&>.html" data-id="<&=itm.petBreedId&>" class="j-link"> <&=itm.name&></a></p>' +
           '<div class="info-itm c">'+
           '<p class="itm-cell"><span class="itm">别名:</span><span class="itm-txt" style="width:300px"><&=itm.alisName&></span></p>'+
           '<&for(var prop=0;prop<baseInfo.length;prop++){if(baseInfo[prop].id!="6"&&baseInfo[prop].id!="14"&&baseInfo[prop].id!="2"&&baseInfo[prop].id!="15"){&><p class="itm-cell">'+
           '<span class="itm"><&=baseInfo[prop].name&>:</span>'+
           '<span class="itm-txt"><&if(baseInfo[prop].id==="2"){&>第<&}&><&=baseInfo[prop].value&><&=baseInfo[prop].unit&></span></p><&};}&></div>' +
           '<a target="_blank" href="/pet/breed-<&=itm.petBreedId&>.html" data-id="<&=itm.petBreedId&>" class="j-link s-link">查看详情&gt;&gt;</a></div></li><&});&></ul>';
       
       var sUrl = pet.request+'api/searchPetData.do';
       function sendAjax() {
            keyword=$('.j-sInput').val();
           $.ajax({
               url: sUrl + "?petRaceId=" + petRaceId + "&pageNum=" + pageNum + "&pageSize="+pet.banpage+"&keyword=" + keyword + "&baseInfo=" + baseInfo.join(',') + "&detailInfo=" + detailInfo.join(',') + "&jsonCallback=?",
               dataType: "jsonp",
               success: function(data) {
                   window.d = data;
                   $('.s-rs-t').html('搜索到 <em>' + data.count + '</em> 条相关记录');
                   if (data.count===0) {
                        $('.s-rs-list').html(sNoTpl);
                   }else{
                        $(data.list).each(function(index, el) {
                            if (el.bodyType) {
                                el.baseData.push({
                                    id: "", name: "体型", value: el.bodyType, unit: ""
                                });
                            }
                            if(el.baseData){
                                el.baseInfo=el.baseData;
                            }else{
                                el.baseInfo=[]
                            }

                        });
                        $('.s-rs-list').html(D.utils.render(sTpl, data));
                    }
                if(cb){cb(pageNum, data)};
               }
           });

       }
       sendAjax();

   }
   var goSearch = function() {
       search(1, function(pageNum, data) {
           console.warn(data.count/pet.banpage);
           laypage({
               cont: 'paging4',
               pages:Math.ceil(data.count/pet.banpage),
              // banpage: pet.banpage,
               curr: curr || 1,
               jump: function(obj,first) {
                   //console.log(obj.curr);
                   if(!first){
                        curr=obj.curr;
                        search(curr);
                    }
               }
           })
       });
   }
   laypage({
               cont: 'paging4',
               pages:Math.ceil(count/pet.banpage),
              // banpage: pet.banpage,
               curr: curr || 1,
               jump: function(obj,first) {
                   //console.log(obj.curr);
                   if(!first){
                        curr=obj.curr;
                        search(curr);
                    }
               }
           });
   //goSearch();
